name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: |
          if [ -f "package.json" ]; then
            npm install
          fi

      - name: Prepare deployment
        run: |
          # Create deployment directory
          mkdir -p _site
          
          # Copy all necessary files
          cp index.html _site/
          cp styles.css _site/
          cp script.js _site/
          cp package.json _site/
          cp README.md _site/
          
          # Copy any additional directories if they exist
          if [ -d "images" ]; then
            cp -r images _site/
          fi
          
          # Verify files are copied
          echo "Deployment directory contents:"
          ls -la _site/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages' 